spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE.URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASS}

jwt:
  secret: ${JWT_SECRET}
  ttl: ${JWT_TTL}

regex:
  email: ${REGEX_EMAIL}
  password: ${REGEX_PASS}

percentage-service:
  cache:
    ttl: ${PERCENTAGE_SERVICE_CACHE_TTL}
  read-timeout: ${PERCENTAGE_SERVICE_READ_TIMEOUT}
  connection-timeout: ${PERCENTAGE_SERVICE_CONNECTION_TIMEOUT}
  url: ${PERCENTAGE_SERVICE_URL}

resilience4j:
  retry:
    instances:
      percentage:
        maxRetryAttempts: ${RETRY_MAX_ATTEMPTS}
        waitDuration: ${RETRY_WAIT_DURATION}
        failAfterMaxAttempts: true

history:
  page-size: ${HISTORY_PAGE_SIZE}